//
//  melice.h
//  Roll
//
//  Created by Raphaël Calabro on 14/03/2022.
//

#ifndef melice_h
#define melice_h

#include "point.h"
#include "quadrilateral.h"
#include "rectangle.h"
#include "size.h"
#include "polar.h"
#include "segment.h"
#include "controller.h"
#include "achievements.h"
#include "base64.h"
#include "crank.h"
#include "inputstream.h"
#include "outputstream.h"
#include "files.h"
#include "keyboard.h"
#include "pdportal.h"
#include "layer.h"
#include "map.h"
#include "layersprite.h"
#include "axe.h"
#include "direction.h"
#include "sprite.h"
#include "spriteinstance.h"
#include "spritetype.h"
#include "subsprite.h"
#include "animation.h"
#include "animationdirection.h"
#include "animationframe.h"
#include "animationtype.h"
#include "loopinganimation.h"
#include "noanimation.h"
#include "playonceanimation.h"
#include "singleframeanimation.h"
#include "synchronizedanimation.h"
#include "animationdefinition.h"
#include "spritedefinition.h"
#include "hitbox.h"
#include "statichitbox.h"
#include "spritehitbox.h"
#include "simplespritehitbox.h"
#include "shootingstyle.h"
#include "shootingstyledefinition.h"
#include "bullet.h"
#include "burstshootingstyle.h"
#include "circularshootingstyle.h"
#include "particuleshootingstyle.h"
#include "simpleshootingstyle.h"
#include "image.h"
#include "text.h"
#include "timer.h"
#include "counter.h"
#include "stride.h"
#include "camera.h"
#include "scene.h"
#include "fadetoblackscene.h"
#include "alignment.h"
#include "achievementtoast.h"
#include "dialog.h"
#include "gridview.h"
#include "nineslice.h"
#include "bitmap.h"
#include "dictionary.h"
#include "hash.h"
#include "eventbus.h"
#include "keyvaluetable.h"
#include "language.h"
#include "list.h"
#include "lcdspriteref.h"
#include "melmath.h"
#include "melstring.h"
#include "metadata.h"
#include "operation.h"
#include "random.h"
#include "screen.h"
#include "uuid.h"

#endif /* melice_h */
